// Electronic product emojis categorized by type - Extended collection (300+ emojis)
export const ELECTRONIC_EMOJIS = {
  // Computers & Laptops
  computers: [
    { emoji: "💻", name: "Laptop", category: "Computers" },
    { emoji: "🖥️", name: "Desktop Computer", category: "Computers" },
    { emoji: "⌨️", name: "Keyboard", category: "Computers" },
    { emoji: "🖱️", name: "Mouse", category: "Computers" },
    { emoji: "🖨️", name: "Printer", category: "Computers" },
    { emoji: "💾", name: "Floppy Disk", category: "Computers" },
    { emoji: "💿", name: "CD/DVD", category: "Computers" },
    { emoji: "📀", name: "DVD", category: "Computers" },
    { emoji: "🖲️", name: "Trackball", category: "Computers" },
    { emoji: "📟", name: "Computer Chip", category: "Computers" },
    { emoji: "🔌", name: "Power Cable", category: "Computers" },
    { emoji: "📊", name: "Monitor Display", category: "Computers" },
    { emoji: "📈", name: "Performance Chart", category: "Computers" },
    { emoji: "💽", name: "Hard Drive", category: "Computers" },
    { emoji: "🧮", name: "Abacus/Calculator", category: "Computers" },
    { emoji: "🔢", name: "Input Numbers", category: "Computers" },
    { emoji: "🔣", name: "Input Symbols", category: "Computers" },
    { emoji: "🔤", name: "Input Letters", category: "Computers" },
  ],

  // Mobile & Communication
  mobile: [
    { emoji: "📱", name: "Mobile Phone", category: "Mobile" },
    { emoji: "📲", name: "Phone with Arrow", category: "Mobile" },
    { emoji: "☎️", name: "Telephone", category: "Mobile" },
    { emoji: "📞", name: "Phone Receiver", category: "Mobile" },
    { emoji: "📟", name: "Pager", category: "Mobile" },
    { emoji: "📠", name: "Fax Machine", category: "Mobile" },
    { emoji: "🔋", name: "Phone Battery", category: "Mobile" },
    { emoji: "📶", name: "Signal Bars", category: "Mobile" },
    { emoji: "📳", name: "Vibration Mode", category: "Mobile" },
    { emoji: "📴", name: "Mobile Off", category: "Mobile" },
    { emoji: "📵", name: "No Mobile Phones", category: "Mobile" },
    { emoji: "🔔", name: "Bell/Notification", category: "Mobile" },
    { emoji: "🔕", name: "Silent Mode", category: "Mobile" },
    { emoji: "🔁", name: "Repeat/Sync", category: "Mobile" },
    { emoji: "🔀", name: "Shuffle", category: "Mobile" },
    { emoji: "⏯️", name: "Play/Pause", category: "Mobile" },
    { emoji: "⏭️", name: "Next Track", category: "Mobile" },
    { emoji: "⏮️", name: "Previous Track", category: "Mobile" },
    { emoji: "⏩", name: "Fast Forward", category: "Mobile" },
    { emoji: "⏪", name: "Rewind", category: "Mobile" },
    { emoji: "📤", name: "Outbox/Upload", category: "Mobile" },
    { emoji: "📥", name: "Inbox/Download", category: "Mobile" },
    { emoji: "✉️", name: "Email/Message", category: "Mobile" },
    { emoji: "📧", name: "Email", category: "Mobile" },
    { emoji: "📨", name: "Incoming Envelope", category: "Mobile" },
    { emoji: "📩", name: "Envelope with Arrow", category: "Mobile" },
  ],

  // Audio & Video
  audioVideo: [
    { emoji: "📺", name: "Television", category: "Audio/Video" },
    { emoji: "📻", name: "Radio", category: "Audio/Video" },
    { emoji: "📹", name: "Video Camera", category: "Audio/Video" },
    { emoji: "📷", name: "Camera", category: "Audio/Video" },
    { emoji: "📸", name: "Camera with Flash", category: "Audio/Video" },
    { emoji: "🎥", name: "Movie Camera", category: "Audio/Video" },
    { emoji: "🎬", name: "Clapper Board", category: "Audio/Video" },
    { emoji: "🎙️", name: "Studio Microphone", category: "Audio/Video" },
    { emoji: "🎚️", name: "Level Slider", category: "Audio/Video" },
    { emoji: "🎛️", name: "Control Knobs", category: "Audio/Video" },
    { emoji: "🎧", name: "Headphone", category: "Audio/Video" },
    { emoji: "🔊", name: "Speaker High Volume", category: "Audio/Video" },
    { emoji: "📢", name: "Loudspeaker", category: "Audio/Video" },
    { emoji: "📣", name: "Megaphone", category: "Audio/Video" },
    { emoji: "🔇", name: "Muted Speaker", category: "Audio/Video" },
    { emoji: "🔈", name: "Speaker Low", category: "Audio/Video" },
    { emoji: "🔉", name: "Speaker Medium", category: "Audio/Video" },
    { emoji: "🎤", name: "Microphone", category: "Audio/Video" },
    { emoji: "🎵", name: "Musical Note", category: "Audio/Video" },
    { emoji: "🎶", name: "Musical Notes", category: "Audio/Video" },
    { emoji: "🎼", name: "Musical Score", category: "Audio/Video" },
    { emoji: "🎹", name: "Musical Keyboard", category: "Audio/Video" },
    { emoji: "🥁", name: "Drum", category: "Audio/Video" },
    { emoji: "🎷", name: "Saxophone", category: "Audio/Video" },
    { emoji: "🎺", name: "Trumpet", category: "Audio/Video" },
    { emoji: "🎸", name: "Guitar", category: "Audio/Video" },
    { emoji: "🪗", name: "Accordion", category: "Audio/Video" },
    { emoji: "🎻", name: "Violin", category: "Audio/Video" },
    { emoji: "🪕", name: "Banjo", category: "Audio/Video" },
    { emoji: "📽️", name: "Film Projector", category: "Audio/Video" },
    { emoji: "🎞️", name: "Film Frames", category: "Audio/Video" },
    { emoji: "📼", name: "Videocassette", category: "Audio/Video" },
    { emoji: "🔴", name: "Record Button", category: "Audio/Video" },
    { emoji: "⏺️", name: "Record", category: "Audio/Video" },
    { emoji: "⏹️", name: "Stop Button", category: "Audio/Video" },
    { emoji: "⏸️", name: "Pause Button", category: "Audio/Video" },
    { emoji: "▶️", name: "Play Button", category: "Audio/Video" },
    { emoji: "⏏️", name: "Eject Button", category: "Audio/Video" },
  ],

  // Gaming & Entertainment
  gaming: [
    { emoji: "🎮", name: "Video Game Controller", category: "Gaming" },
    { emoji: "🕹️", name: "Joystick", category: "Gaming" },
    { emoji: "🎯", name: "Direct Hit", category: "Gaming" },
    { emoji: "🎲", name: "Game Die", category: "Gaming" },
    { emoji: "🎰", name: "Slot Machine", category: "Gaming" },
    { emoji: "🎳", name: "Bowling", category: "Gaming" },
    { emoji: "🧩", name: "Puzzle Piece", category: "Gaming" },
    { emoji: "♟️", name: "Chess Pawn", category: "Gaming" },
    { emoji: "🃏", name: "Joker Card", category: "Gaming" },
    { emoji: "🀄", name: "Mahjong Tile", category: "Gaming" },
    { emoji: "🎴", name: "Flower Playing Cards", category: "Gaming" },
    { emoji: "🎪", name: "Circus Tent", category: "Gaming" },
    { emoji: "🎠", name: "Carousel Horse", category: "Gaming" },
    { emoji: "🎡", name: "Ferris Wheel", category: "Gaming" },
    { emoji: "🎢", name: "Roller Coaster", category: "Gaming" },
    { emoji: "🏆", name: "Trophy", category: "Gaming" },
    { emoji: "🥇", name: "Gold Medal", category: "Gaming" },
    { emoji: "🥈", name: "Silver Medal", category: "Gaming" },
    { emoji: "🥉", name: "Bronze Medal", category: "Gaming" },
    { emoji: "🏅", name: "Sports Medal", category: "Gaming" },
    { emoji: "🎖️", name: "Military Medal", category: "Gaming" },
  ],

  // Storage & Memory
  storage: [
    { emoji: "💽", name: "Computer Disk", category: "Storage" },
    { emoji: "💾", name: "Floppy Disk", category: "Storage" },
    { emoji: "💿", name: "Optical Disk", category: "Storage" },
    { emoji: "📀", name: "DVD", category: "Storage" },
    { emoji: "🗂️", name: "Card Index Dividers", category: "Storage" },
    { emoji: "🗃️", name: "Card File Box", category: "Storage" },
    { emoji: "🗄️", name: "File Cabinet", category: "Storage" },
    { emoji: "📁", name: "File Folder", category: "Storage" },
    { emoji: "📂", name: "Open File Folder", category: "Storage" },
    { emoji: "📋", name: "Clipboard", category: "Storage" },
    { emoji: "📑", name: "Bookmark Tabs", category: "Storage" },
    { emoji: "📓", name: "Notebook", category: "Storage" },
    { emoji: "📔", name: "Notebook Decorative", category: "Storage" },
    { emoji: "📒", name: "Ledger", category: "Storage" },
    { emoji: "📕", name: "Closed Book", category: "Storage" },
    { emoji: "📗", name: "Green Book", category: "Storage" },
    { emoji: "📘", name: "Blue Book", category: "Storage" },
    { emoji: "📙", name: "Orange Book", category: "Storage" },
    { emoji: "📚", name: "Books", category: "Storage" },
  ],

  // Home Appliances - AC, Cooler, Fridge, Washing Machine, etc.
  appliances: [
    { emoji: "❄️", name: "Air Conditioner/Snowflake", category: "Appliances" },
    { emoji: "🌬️", name: "Air Cooler/Wind Face", category: "Appliances" },
    { emoji: "🧊", name: "Ice Cube/Cooling", category: "Appliances" },
    { emoji: "🍽️", name: "Dishwasher/Plate", category: "Appliances" },
    { emoji: "🧼", name: "Washing/Soap", category: "Appliances" },
    { emoji: "🧺", name: "Laundry Basket", category: "Appliances" },
    { emoji: "🧴", name: "Lotion Bottle", category: "Appliances" },
    { emoji: "🧽", name: "Sponge", category: "Appliances" },
    { emoji: "🧹", name: "Broom/Vacuum", category: "Appliances" },
    { emoji: "🧪", name: "Test Tube", category: "Appliances" },
    { emoji: "🌡️", name: "Thermometer", category: "Appliances" },
    { emoji: "💧", name: "Water Drop", category: "Appliances" },
    { emoji: "💦", name: "Sweat Droplets", category: "Appliances" },
    { emoji: "🔥", name: "Fire/Heater", category: "Appliances" },
    { emoji: "🌪️", name: "Tornado/Fan", category: "Appliances" },
    { emoji: "☀️", name: "Sun/Solar", category: "Appliances" },
    { emoji: "🌙", name: "Moon/Night Mode", category: "Appliances" },
    { emoji: "⭐", name: "Star/Premium", category: "Appliances" },
    { emoji: "✨", name: "Sparkles/Clean", category: "Appliances" },
    { emoji: "🔌", name: "Electric Plug", category: "Appliances" },
    { emoji: "💡", name: "Light Bulb", category: "Appliances" },
    { emoji: "🔦", name: "Flashlight", category: "Appliances" },
    { emoji: "🕯️", name: "Candle", category: "Appliances" },
    { emoji: "🧯", name: "Fire Extinguisher", category: "Appliances" },
    { emoji: "🔋", name: "Battery", category: "Appliances" },
    { emoji: "🪫", name: "Low Battery", category: "Appliances" },
    { emoji: "⚡", name: "High Voltage/Power", category: "Appliances" },
    { emoji: "🛁", name: "Bathtub/Geyser", category: "Appliances" },
    { emoji: "🚿", name: "Shower", category: "Appliances" },
    { emoji: "🪥", name: "Toothbrush", category: "Appliances" },
    { emoji: "🪒", name: "Razor/Trimmer", category: "Appliances" },
    { emoji: "💈", name: "Barber Pole", category: "Appliances" },
    { emoji: "🧻", name: "Toilet Paper", category: "Appliances" },
    { emoji: "🚽", name: "Toilet", category: "Appliances" },
    { emoji: "🪠", name: "Plunger", category: "Appliances" },
    { emoji: "🚰", name: "Potable Water", category: "Appliances" },
    { emoji: "🏠", name: "House", category: "Appliances" },
    { emoji: "🏡", name: "House with Garden", category: "Appliances" },
    { emoji: "🏢", name: "Office Building", category: "Appliances" },
    { emoji: "🛋️", name: "Couch/Furniture", category: "Appliances" },
    { emoji: "🪑", name: "Chair", category: "Appliances" },
    { emoji: "🛏️", name: "Bed", category: "Appliances" },
    { emoji: "🛌", name: "Person in Bed", category: "Appliances" },
    { emoji: "🪟", name: "Window", category: "Appliances" },
    { emoji: "🪞", name: "Mirror", category: "Appliances" },
    { emoji: "🚪", name: "Door", category: "Appliances" },
    { emoji: "🧸", name: "Teddy Bear", category: "Appliances" },
    { emoji: "🪆", name: "Nesting Dolls", category: "Appliances" },
    { emoji: "🖼️", name: "Framed Picture", category: "Appliances" },
    { emoji: "🛒", name: "Shopping Cart", category: "Appliances" },
    { emoji: "🎁", name: "Gift/Package", category: "Appliances" },
    { emoji: "🎈", name: "Balloon", category: "Appliances" },
    { emoji: "🎉", name: "Party Popper", category: "Appliances" },
    { emoji: "🎊", name: "Confetti Ball", category: "Appliances" },
    { emoji: "🪴", name: "Potted Plant", category: "Appliances" },
    { emoji: "🌱", name: "Seedling", category: "Appliances" },
    { emoji: "🌿", name: "Herb", category: "Appliances" },
  ],

  // Kitchen & Cooking Appliances
  kitchen: [
    { emoji: "🍳", name: "Cooking/Induction", category: "Kitchen" },
    { emoji: "🔪", name: "Kitchen Knife", category: "Kitchen" },
    { emoji: "🥄", name: "Spoon", category: "Kitchen" },
    { emoji: "🍴", name: "Fork and Knife", category: "Kitchen" },
    { emoji: "🥢", name: "Chopsticks", category: "Kitchen" },
    { emoji: "🧂", name: "Salt", category: "Kitchen" },
    { emoji: "🫕", name: "Fondue/Slow Cooker", category: "Kitchen" },
    { emoji: "🍲", name: "Pot of Food", category: "Kitchen" },
    { emoji: "🥘", name: "Shallow Pan/Kadai", category: "Kitchen" },
    { emoji: "🍱", name: "Bento Box/Container", category: "Kitchen" },
    { emoji: "🥡", name: "Takeout Box", category: "Kitchen" },
    { emoji: "☕", name: "Coffee Maker", category: "Kitchen" },
    { emoji: "🫖", name: "Teapot/Kettle", category: "Kitchen" },
    { emoji: "🧃", name: "Juice/Beverage Box", category: "Kitchen" },
    { emoji: "🧋", name: "Bubble Tea", category: "Kitchen" },
    { emoji: "🥤", name: "Cup with Straw", category: "Kitchen" },
    { emoji: "🍶", name: "Sake Bottle", category: "Kitchen" },
    { emoji: "🍺", name: "Beer Mug", category: "Kitchen" },
    { emoji: "🍻", name: "Clinking Beer Mugs", category: "Kitchen" },
    { emoji: "🥂", name: "Clinking Glasses", category: "Kitchen" },
    { emoji: "🍷", name: "Wine Glass", category: "Kitchen" },
    { emoji: "🥃", name: "Tumbler Glass", category: "Kitchen" },
    { emoji: "🍸", name: "Cocktail Glass", category: "Kitchen" },
    { emoji: "🍹", name: "Tropical Drink", category: "Kitchen" },
    { emoji: "🧉", name: "Mate", category: "Kitchen" },
    { emoji: "🍾", name: "Bottle with Cork", category: "Kitchen" },
    { emoji: "🫗", name: "Pouring Liquid", category: "Kitchen" },
    { emoji: "🥛", name: "Glass of Milk", category: "Kitchen" },
    { emoji: "🍼", name: "Baby Bottle", category: "Kitchen" },
    { emoji: "🍵", name: "Teacup", category: "Kitchen" },
    { emoji: "🧇", name: "Waffle Maker", category: "Kitchen" },
    { emoji: "🥞", name: "Pancakes", category: "Kitchen" },
    { emoji: "🧈", name: "Butter", category: "Kitchen" },
    { emoji: "🍞", name: "Bread/Toaster", category: "Kitchen" },
    { emoji: "🥖", name: "Baguette Bread", category: "Kitchen" },
    { emoji: "🥨", name: "Pretzel", category: "Kitchen" },
    { emoji: "🥯", name: "Bagel", category: "Kitchen" },
    { emoji: "🧀", name: "Cheese", category: "Kitchen" },
    { emoji: "🥚", name: "Egg", category: "Kitchen" },
    { emoji: "🍗", name: "Poultry Leg", category: "Kitchen" },
    { emoji: "🍖", name: "Meat on Bone", category: "Kitchen" },
    { emoji: "🥩", name: "Cut of Meat", category: "Kitchen" },
    { emoji: "🥓", name: "Bacon", category: "Kitchen" },
    { emoji: "🍔", name: "Hamburger", category: "Kitchen" },
    { emoji: "🍟", name: "French Fries", category: "Kitchen" },
    { emoji: "🍕", name: "Pizza/Oven", category: "Kitchen" },
    { emoji: "🌭", name: "Hot Dog", category: "Kitchen" },
    { emoji: "🥪", name: "Sandwich Maker", category: "Kitchen" },
    { emoji: "🌮", name: "Taco", category: "Kitchen" },
    { emoji: "🌯", name: "Burrito", category: "Kitchen" },
    { emoji: "🫔", name: "Tamale", category: "Kitchen" },
    { emoji: "🥙", name: "Stuffed Flatbread", category: "Kitchen" },
    { emoji: "🧆", name: "Falafel", category: "Kitchen" },
    { emoji: "🍿", name: "Popcorn/Popcorn Maker", category: "Kitchen" },
    { emoji: "🍦", name: "Ice Cream", category: "Kitchen" },
    { emoji: "🍧", name: "Shaved Ice", category: "Kitchen" },
    { emoji: "🍨", name: "Ice Cream Maker", category: "Kitchen" },
    { emoji: "🍩", name: "Doughnut", category: "Kitchen" },
    { emoji: "🍪", name: "Cookie", category: "Kitchen" },
    { emoji: "🎂", name: "Birthday Cake", category: "Kitchen" },
    { emoji: "🍰", name: "Shortcake", category: "Kitchen" },
    { emoji: "🧁", name: "Cupcake", category: "Kitchen" },
    { emoji: "🥧", name: "Pie", category: "Kitchen" },
    { emoji: "🍫", name: "Chocolate Bar", category: "Kitchen" },
    { emoji: "🍬", name: "Candy", category: "Kitchen" },
    { emoji: "🍭", name: "Lollipop", category: "Kitchen" },
    { emoji: "🍮", name: "Custard", category: "Kitchen" },
    { emoji: "🍯", name: "Honey Pot", category: "Kitchen" },
    { emoji: "🥣", name: "Bowl with Spoon", category: "Kitchen" },
    { emoji: "🥗", name: "Green Salad", category: "Kitchen" },
    { emoji: "🍝", name: "Spaghetti", category: "Kitchen" },
    { emoji: "🍜", name: "Steaming Bowl", category: "Kitchen" },
    { emoji: "🍛", name: "Curry Rice", category: "Kitchen" },
    { emoji: "🍚", name: "Cooked Rice", category: "Kitchen" },
    { emoji: "🍙", name: "Rice Ball", category: "Kitchen" },
    { emoji: "🍘", name: "Rice Cracker", category: "Kitchen" },
    { emoji: "🍢", name: "Oden", category: "Kitchen" },
    { emoji: "🍡", name: "Dango", category: "Kitchen" },
    { emoji: "🍣", name: "Sushi", category: "Kitchen" },
    { emoji: "🍤", name: "Fried Shrimp", category: "Kitchen" },
    { emoji: "🍥", name: "Fish Cake", category: "Kitchen" },
    { emoji: "🥮", name: "Moon Cake", category: "Kitchen" },
    { emoji: "🥟", name: "Dumpling", category: "Kitchen" },
    { emoji: "🥠", name: "Fortune Cookie", category: "Kitchen" },
    { emoji: "🥫", name: "Canned Food", category: "Kitchen" },
    { emoji: "🫙", name: "Jar", category: "Kitchen" },
    { emoji: "🫛", name: "Pea Pod", category: "Kitchen" },
    { emoji: "🫑", name: "Bell Pepper", category: "Kitchen" },
    { emoji: "🧅", name: "Onion", category: "Kitchen" },
    { emoji: "🧄", name: "Garlic", category: "Kitchen" },
    { emoji: "🥕", name: "Carrot", category: "Kitchen" },
    { emoji: "🥔", name: "Potato", category: "Kitchen" },
    { emoji: "🍠", name: "Roasted Sweet Potato", category: "Kitchen" },
    { emoji: "🥒", name: "Cucumber", category: "Kitchen" },
    { emoji: "🌶️", name: "Hot Pepper", category: "Kitchen" },
    { emoji: "🫚", name: "Ginger", category: "Kitchen" },
    { emoji: "🌽", name: "Ear of Corn", category: "Kitchen" },
    { emoji: "🥦", name: "Broccoli", category: "Kitchen" },
    { emoji: "🥬", name: "Leafy Green", category: "Kitchen" },
    { emoji: "🍄", name: "Mushroom", category: "Kitchen" },
    { emoji: "🥜", name: "Peanuts", category: "Kitchen" },
    { emoji: "🌰", name: "Chestnut", category: "Kitchen" },
    { emoji: "🫘", name: "Beans", category: "Kitchen" },
  ],

  // Watches & Time Devices
  watches: [
    { emoji: "⌚", name: "Watch/Smartwatch", category: "Watches" },
    { emoji: "⏰", name: "Alarm Clock", category: "Watches" },
    { emoji: "⏱️", name: "Stopwatch", category: "Watches" },
    { emoji: "⏲️", name: "Timer Clock", category: "Watches" },
    { emoji: "🕰️", name: "Mantelpiece Clock", category: "Watches" },
    { emoji: "🕛", name: "Twelve O'Clock", category: "Watches" },
    { emoji: "🕧", name: "Twelve-Thirty", category: "Watches" },
    { emoji: "🕐", name: "One O'Clock", category: "Watches" },
    { emoji: "🕜", name: "One-Thirty", category: "Watches" },
    { emoji: "🕑", name: "Two O'Clock", category: "Watches" },
    { emoji: "🕝", name: "Two-Thirty", category: "Watches" },
    { emoji: "🕒", name: "Three O'Clock", category: "Watches" },
    { emoji: "🕞", name: "Three-Thirty", category: "Watches" },
    { emoji: "🕓", name: "Four O'Clock", category: "Watches" },
    { emoji: "🕟", name: "Four-Thirty", category: "Watches" },
    { emoji: "🕔", name: "Five O'Clock", category: "Watches" },
    { emoji: "🕠", name: "Five-Thirty", category: "Watches" },
    { emoji: "🕕", name: "Six O'Clock", category: "Watches" },
    { emoji: "🕡", name: "Six-Thirty", category: "Watches" },
    { emoji: "⏳", name: "Hourglass Running", category: "Watches" },
    { emoji: "⌛", name: "Hourglass Done", category: "Watches" },
    { emoji: "📅", name: "Calendar", category: "Watches" },
    { emoji: "📆", name: "Tear-Off Calendar", category: "Watches" },
    { emoji: "🗓️", name: "Spiral Calendar", category: "Watches" },
    { emoji: "📇", name: "Card Index", category: "Watches" },
  ],

  // Tools & Hardware
  tools: [
    { emoji: "🔭", name: "Telescope", category: "Tools" },
    { emoji: "🔬", name: "Microscope", category: "Tools" },
    { emoji: "📡", name: "Satellite Antenna", category: "Tools" },
    { emoji: "🛰️", name: "Satellite", category: "Tools" },
    { emoji: "🧲", name: "Magnet", category: "Tools" },
    { emoji: "🔩", name: "Nut and Bolt", category: "Tools" },
    { emoji: "⚙️", name: "Gear/Settings", category: "Tools" },
    { emoji: "🔧", name: "Wrench", category: "Tools" },
    { emoji: "🔨", name: "Hammer", category: "Tools" },
    { emoji: "🪛", name: "Screwdriver", category: "Tools" },
    { emoji: "🪚", name: "Carpentry Saw", category: "Tools" },
    { emoji: "🔗", name: "Link/Chain", category: "Tools" },
    { emoji: "⛓️", name: "Chains", category: "Tools" },
    { emoji: "🪝", name: "Hook", category: "Tools" },
    { emoji: "🧰", name: "Toolbox", category: "Tools" },
    { emoji: "🪤", name: "Mouse Trap", category: "Tools" },
    { emoji: "🗜️", name: "Clamp", category: "Tools" },
    { emoji: "⚖️", name: "Balance Scale", category: "Tools" },
    { emoji: "🦯", name: "White Cane", category: "Tools" },
    { emoji: "🔍", name: "Magnifying Glass Left", category: "Tools" },
    { emoji: "🔎", name: "Magnifying Glass Right", category: "Tools" },
    { emoji: "🕳️", name: "Hole", category: "Tools" },
    { emoji: "💉", name: "Syringe", category: "Tools" },
    { emoji: "🩸", name: "Drop of Blood", category: "Tools" },
    { emoji: "💊", name: "Pill", category: "Tools" },
    { emoji: "🩹", name: "Adhesive Bandage", category: "Tools" },
    { emoji: "🩺", name: "Stethoscope", category: "Tools" },
    { emoji: "🩻", name: "X-Ray", category: "Tools" },
    { emoji: "🥽", name: "Goggles", category: "Tools" },
    { emoji: "🥼", name: "Lab Coat", category: "Tools" },
    { emoji: "🦺", name: "Safety Vest", category: "Tools" },
    { emoji: "⛑️", name: "Rescue Worker Helmet", category: "Tools" },
    { emoji: "🪖", name: "Military Helmet", category: "Tools" },
    { emoji: "🎓", name: "Graduation Cap", category: "Tools" },
    { emoji: "👓", name: "Glasses", category: "Tools" },
    { emoji: "🕶️", name: "Sunglasses", category: "Tools" },
  ],

  // Transportation & Vehicles (Electric/Electronic)
  vehicles: [
    { emoji: "🚗", name: "Automobile", category: "Vehicles" },
    { emoji: "🚕", name: "Taxi", category: "Vehicles" },
    { emoji: "🚙", name: "Sport Utility Vehicle", category: "Vehicles" },
    { emoji: "🛻", name: "Pickup Truck", category: "Vehicles" },
    { emoji: "🚌", name: "Bus", category: "Vehicles" },
    { emoji: "🚎", name: "Trolleybus", category: "Vehicles" },
    { emoji: "🏎️", name: "Racing Car", category: "Vehicles" },
    { emoji: "🚓", name: "Police Car", category: "Vehicles" },
    { emoji: "🚑", name: "Ambulance", category: "Vehicles" },
    { emoji: "🚒", name: "Fire Engine", category: "Vehicles" },
    { emoji: "🚐", name: "Minibus", category: "Vehicles" },
    { emoji: "🚚", name: "Delivery Truck", category: "Vehicles" },
    { emoji: "🚛", name: "Articulated Lorry", category: "Vehicles" },
    { emoji: "🚜", name: "Tractor", category: "Vehicles" },
    { emoji: "🏍️", name: "Motorcycle", category: "Vehicles" },
    { emoji: "🛵", name: "Motor Scooter", category: "Vehicles" },
    { emoji: "🚲", name: "Bicycle", category: "Vehicles" },
    { emoji: "🛴", name: "Kick Scooter", category: "Vehicles" },
    { emoji: "🛹", name: "Skateboard", category: "Vehicles" },
    { emoji: "🛼", name: "Roller Skate", category: "Vehicles" },
    { emoji: "🚁", name: "Helicopter", category: "Vehicles" },
    { emoji: "✈️", name: "Airplane", category: "Vehicles" },
    { emoji: "🛩️", name: "Small Airplane", category: "Vehicles" },
    { emoji: "🛫", name: "Airplane Departure", category: "Vehicles" },
    { emoji: "🛬", name: "Airplane Arrival", category: "Vehicles" },
    { emoji: "🚀", name: "Rocket", category: "Vehicles" },
    { emoji: "🛸", name: "Flying Saucer", category: "Vehicles" },
    { emoji: "🚢", name: "Ship", category: "Vehicles" },
    { emoji: "⛵", name: "Sailboat", category: "Vehicles" },
    { emoji: "🚤", name: "Speedboat", category: "Vehicles" },
    { emoji: "🛥️", name: "Motor Boat", category: "Vehicles" },
    { emoji: "🛳️", name: "Passenger Ship", category: "Vehicles" },
    { emoji: "⛴️", name: "Ferry", category: "Vehicles" },
    { emoji: "🚂", name: "Locomotive", category: "Vehicles" },
    { emoji: "🚃", name: "Railway Car", category: "Vehicles" },
    { emoji: "🚄", name: "High-Speed Train", category: "Vehicles" },
    { emoji: "🚅", name: "Bullet Train", category: "Vehicles" },
    { emoji: "🚆", name: "Train", category: "Vehicles" },
    { emoji: "🚇", name: "Metro", category: "Vehicles" },
    { emoji: "🚈", name: "Light Rail", category: "Vehicles" },
    { emoji: "🚝", name: "Monorail", category: "Vehicles" },
    { emoji: "🚞", name: "Mountain Railway", category: "Vehicles" },
    { emoji: "🚋", name: "Tram Car", category: "Vehicles" },
    { emoji: "🚊", name: "Tram", category: "Vehicles" },
    { emoji: "🚉", name: "Station", category: "Vehicles" },
    { emoji: "🛞", name: "Wheel", category: "Vehicles" },
    { emoji: "⛽", name: "Fuel Pump", category: "Vehicles" },
    { emoji: "🛣️", name: "Motorway", category: "Vehicles" },
    { emoji: "🛤️", name: "Railway Track", category: "Vehicles" },
    { emoji: "🚏", name: "Bus Stop", category: "Vehicles" },
    { emoji: "⚓", name: "Anchor", category: "Vehicles" },
    { emoji: "🚧", name: "Construction", category: "Vehicles" },
  ],

  // Security & Safety
  security: [
    { emoji: "🔒", name: "Locked/Secure", category: "Security" },
    { emoji: "🔓", name: "Unlocked", category: "Security" },
    { emoji: "🔐", name: "Locked with Key", category: "Security" },
    { emoji: "🔑", name: "Key", category: "Security" },
    { emoji: "🗝️", name: "Old Key", category: "Security" },
    { emoji: "🔏", name: "Locked with Pen", category: "Security" },
    { emoji: "🛡️", name: "Shield", category: "Security" },
    { emoji: "⚔️", name: "Crossed Swords", category: "Security" },
    { emoji: "🗡️", name: "Dagger", category: "Security" },
    { emoji: "💣", name: "Bomb", category: "Security" },
    { emoji: "🧨", name: "Firecracker", category: "Security" },
    { emoji: "🪃", name: "Boomerang", category: "Security" },
    { emoji: "🏹", name: "Bow and Arrow", category: "Security" },
    { emoji: "🔫", name: "Pistol", category: "Security" },
    { emoji: "🚨", name: "Police Car Light", category: "Security" },
    { emoji: "🔔", name: "Bell", category: "Security" },
    { emoji: "🔕", name: "Bell with Slash", category: "Security" },
    { emoji: "📯", name: "Postal Horn", category: "Security" },
    { emoji: "🚪", name: "Door", category: "Security" },
    { emoji: "🛗", name: "Elevator", category: "Security" },
    { emoji: "🚭", name: "No Smoking", category: "Security" },
    { emoji: "🚫", name: "Prohibited", category: "Security" },
    { emoji: "⛔", name: "No Entry", category: "Security" },
    { emoji: "🚳", name: "No Bicycles", category: "Security" },
    { emoji: "🚱", name: "Non-Potable Water", category: "Security" },
    { emoji: "🚯", name: "No Littering", category: "Security" },
    { emoji: "🚷", name: "No Pedestrians", category: "Security" },
    { emoji: "⚠️", name: "Warning", category: "Security" },
    { emoji: "☢️", name: "Radioactive", category: "Security" },
    { emoji: "☣️", name: "Biohazard", category: "Security" },
    { emoji: "✅", name: "Check Mark", category: "Security" },
    { emoji: "❌", name: "Cross Mark", category: "Security" },
    { emoji: "❓", name: "Question Mark", category: "Security" },
    { emoji: "❗", name: "Exclamation Mark", category: "Security" },
    { emoji: "ℹ️", name: "Information", category: "Security" },
  ],

  // General Tech & Symbols
  tech: [
    { emoji: "📦", name: "Package/Box", category: "General" },
    { emoji: "📫", name: "Mailbox", category: "General" },
    { emoji: "📪", name: "Mailbox Closed", category: "General" },
    { emoji: "📬", name: "Mailbox Open", category: "General" },
    { emoji: "📭", name: "Mailbox No Mail", category: "General" },
    { emoji: "📮", name: "Postbox", category: "General" },
    { emoji: "🏷️", name: "Label/Tag", category: "General" },
    { emoji: "📄", name: "Document", category: "General" },
    { emoji: "📃", name: "Page with Curl", category: "General" },
    { emoji: "📜", name: "Scroll", category: "General" },
    { emoji: "📰", name: "Newspaper", category: "General" },
    { emoji: "🗞️", name: "Rolled Newspaper", category: "General" },
    { emoji: "✏️", name: "Pencil", category: "General" },
    { emoji: "✒️", name: "Black Nib", category: "General" },
    { emoji: "🖊️", name: "Pen", category: "General" },
    { emoji: "🖋️", name: "Fountain Pen", category: "General" },
    { emoji: "🖌️", name: "Paintbrush", category: "General" },
    { emoji: "🖍️", name: "Crayon", category: "General" },
    { emoji: "📝", name: "Memo", category: "General" },
    { emoji: "📌", name: "Pushpin", category: "General" },
    { emoji: "📍", name: "Round Pushpin", category: "General" },
    { emoji: "📎", name: "Paperclip", category: "General" },
    { emoji: "🖇️", name: "Linked Paperclips", category: "General" },
    { emoji: "📏", name: "Straight Ruler", category: "General" },
    { emoji: "📐", name: "Triangular Ruler", category: "General" },
    { emoji: "✂️", name: "Scissors", category: "General" },
    { emoji: "🗑️", name: "Wastebasket", category: "General" },
    { emoji: "🗳️", name: "Ballot Box", category: "General" },
    { emoji: "🔖", name: "Bookmark", category: "General" },
    { emoji: "🏧", name: "ATM Sign", category: "General" },
    { emoji: "💰", name: "Money Bag", category: "General" },
    { emoji: "💵", name: "Dollar Banknote", category: "General" },
    { emoji: "💴", name: "Yen Banknote", category: "General" },
    { emoji: "💶", name: "Euro Banknote", category: "General" },
    { emoji: "💷", name: "Pound Banknote", category: "General" },
    { emoji: "💸", name: "Money with Wings", category: "General" },
    { emoji: "💳", name: "Credit Card", category: "General" },
    { emoji: "🧾", name: "Receipt", category: "General" },
    { emoji: "💹", name: "Chart Increasing", category: "General" },
    { emoji: "🪙", name: "Coin", category: "General" },
    { emoji: "🔲", name: "Black Square Button", category: "General" },
    { emoji: "🔳", name: "White Square Button", category: "General" },
    { emoji: "⬛", name: "Black Large Square", category: "General" },
    { emoji: "⬜", name: "White Large Square", category: "General" },
    { emoji: "◼️", name: "Black Medium Square", category: "General" },
    { emoji: "◻️", name: "White Medium Square", category: "General" },
    { emoji: "◾", name: "Black Medium-Small Square", category: "General" },
    { emoji: "◽", name: "White Medium-Small Square", category: "General" },
    { emoji: "▪️", name: "Black Small Square", category: "General" },
    { emoji: "▫️", name: "White Small Square", category: "General" },
    { emoji: "🔶", name: "Large Orange Diamond", category: "General" },
    { emoji: "🔷", name: "Large Blue Diamond", category: "General" },
    { emoji: "🔸", name: "Small Orange Diamond", category: "General" },
    { emoji: "🔹", name: "Small Blue Diamond", category: "General" },
    { emoji: "🔺", name: "Red Triangle Up", category: "General" },
    { emoji: "🔻", name: "Red Triangle Down", category: "General" },
    { emoji: "💠", name: "Diamond with Dot", category: "General" },
    { emoji: "🔘", name: "Radio Button", category: "General" },
    { emoji: "🔵", name: "Blue Circle", category: "General" },
    { emoji: "🟢", name: "Green Circle", category: "General" },
    { emoji: "🟡", name: "Yellow Circle", category: "General" },
    { emoji: "🟠", name: "Orange Circle", category: "General" },
    { emoji: "🔴", name: "Red Circle", category: "General" },
    { emoji: "⚪", name: "White Circle", category: "General" },
    { emoji: "⚫", name: "Black Circle", category: "General" },
    { emoji: "🟣", name: "Purple Circle", category: "General" },
    { emoji: "🟤", name: "Brown Circle", category: "General" },
  ],
}

// Flatten all emojis into a single array
export const ALL_ELECTRONIC_EMOJIS = Object.values(ELECTRONIC_EMOJIS).flat()

// Get emojis by category
export const getEmojisByCategory = (category: keyof typeof ELECTRONIC_EMOJIS) => {
  return ELECTRONIC_EMOJIS[category] || []
}

// Search emojis by name
export const searchEmojis = (query: string) => {
  const lowerQuery = query.toLowerCase()
  return ALL_ELECTRONIC_EMOJIS.filter(
    (item) =>
      item.name.toLowerCase().includes(lowerQuery) ||
      item.category.toLowerCase().includes(lowerQuery)
  )
}

// Get all categories
export const EMOJI_CATEGORIES = [
  { key: "appliances", label: "🏠 Home Appliances (AC, Cooler, Fridge, etc.)" },
  { key: "kitchen", label: "🍳 Kitchen & Cooking" },
  { key: "computers", label: "💻 Computers & Laptops" },
  { key: "mobile", label: "📱 Mobile & Communication" },
  { key: "audioVideo", label: "📺 Audio & Video (TV, Camera, etc.)" },
  { key: "gaming", label: "🎮 Gaming & Entertainment" },
  { key: "storage", label: "💾 Storage & Memory" },
  { key: "watches", label: "⌚ Watches & Time" },
  { key: "tools", label: "🔧 Tools & Hardware" },
  { key: "vehicles", label: "🚗 Vehicles & Transportation" },
  { key: "security", label: "🔒 Security & Safety" },
  { key: "tech", label: "📦 General Tech & Symbols" },
] as const
