const { chromium } = require('C:\\Users\\nabap\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\node\\node_modules\\.pnpm\\playwright-core@1.60.0\\node_modules\\playwright-core');
const fs = require('fs');
const path = require('path');
let pageNum = 0;
const pages = [];
function W() {}
W.page = (title, icon, role, ...content) => { pageNum++; return `<div class="page"><div class="page-header"><span class="icon">${icon}</span><h2>${title}</h2>${role?`<span class="role">${role}</span>`:''}</div>${content.join('')}<div class="pn">${pageNum}</div></div>`; };
W.cover = (t, s, m) => `<div class="cover"><div class="logo-text">SARA ELECTRONICS</div><h1>${t}</h1><h2>${s}</h2><div class="meta">${m}</div></div>`;
W.sec = (t, ...c) => `<div class="section"><div class="sec-title">${t}</div>${c.join('')}</div>`;
W.grid = (cls, ...items) => `<div class="grid ${cls}">${items.join('')}</div>`;
W.card = (t, d, c='') => `<div class="card ${c}"><h4>${t}</h4><p>${d}</p></div>`;
W.ci = (i, t, d, c='') => `<div class="card ${c}"><div style="font-size:14px;margin-bottom:4px">${i}</div><h4>${t}</h4><p>${d}</p></div>`;
W.badge = (t, c='bg-gray-100 text-gray-600') => `<span class="badge ${c}">${t}</span>`;
W.btn = (t, c='btn-primary', s='') => `<span class="btn ${c} ${s}">${t}</span>`;
W.kpi = (v, l, c='') => `<div class="kpi ${c}"><div class="val">${v}</div><div class="lbl">${l}</div></div>`;
W.kpiG = (...i) => `<div class="kpi-grid">${i.join('')}</div>`;
W.tbl = (h, r) => `<table class="tbl"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
W.sb = (items, a=0) => `<div class="sidebar">${items.map((it,i)=>{if(it.s)return`<div class="sb-sec">${it.s}</div>`;return`<div class="sb-item ${i===a?'active':''}">${it.i||''} ${it.l}</div>`;}).join('')}</div>`;
W.topbar = (logo, nav, right) => `<div class="topbar"><span class="logo">${logo}</span><span class="search">Search products, brands and more...</span>${(nav||[]).map(n=>`<span class="nav-item">${n}</span>`).join('')}<div class="icons">${(right||[]).join('')}</div></div>`;
W.prod = (n, p, op, r, img='📦') => `<div class="prod-card"><div class="img">${img}</div><div class="info"><div class="name">${n}</div><div><span class="price">${p}</span>${op?`<span class="old-price">${op}</span>`:''}</div><div class="rating">${'★'.repeat(Math.floor(r||4))}${'☆'.repeat(5-Math.floor(r||4))} <span style="color:#94a3b8">(${r||4.0})</span></div><div class="btn-add">Add to Cart</div></div></div>`;
W.alert = (t, c='info') => `<div class="alert alert-${c}">${t}</div>`;
W.fg = (l, tp='text', ph='') => `<div class="fg"><label>${l}</label><input class="fi" type="${tp}" placeholder="${ph||l}"></div>`;
W.fr = (...f) => `<div class="fr">${f.join('')}</div>`;
W.tabs = (items, a=0) => `<div class="tabs">${items.map((t,i)=>`<span class="tab ${i===a?'active':''}">${t}</span>`).join('')}</div>`;
W.toolbar = (t, ...b) => `<div class="toolbar"><span class="tb-title">${t}</span><div style="margin-left:auto;display:flex;gap:4px">${b.join('')}</div></div>`;
W.steps = (items, a=0) => `<div class="steps">${items.map((s,i)=>`<div class="step ${i<a?'done':''} ${i===a?'active':''}"><span class="circle">${i<a?'✓':i+1}</span><div class="sl">${s}</div></div>`).join('')}</div>`;
W.progress = (p, c='fill-blue') => `<div class="pbar"><div class="fill ${c}" style="width:${p}%"></div></div>`;
W.twoCol = (l, r) => `<div class="two-col"><div>${l}</div><div>${r}</div></div>`;
W.threeCol = (...c) => `<div class="three-col">${c.join('')}</div>`;
W.breadcrumb = (...items) => `<div class="breadcrumb">${items.map((b,i)=>i<items.length-1?`${b} › `:`<span>${b}</span>`).join('')}</div>`;
W.miniChart = (...h) => `<div class="mini-chart">${h.map(x=>`<div class="bar" style="height:${x}px"></div>`).join('')}</div>`;
W.code = (t) => `<div class="code-block">${t}</div>`;
W.codeR = (t) => `<div class="code-resp">${t}</div>`;
W.donut = () => `<div class="donut"></div>`;
W.accordion = (t, c) => `<div class="accordion"><div class="acc-header"><span>${t}</span><span>▼</span></div><div class="acc-body">${c}</div></div>`;
W.timeline = (...items) => `<div class="timeline">${items.map(i=>`<div class="tl-item"><div class="tl-time">${i.time}</div><div class="tl-event">${i.event}</div></div>`).join('')}</div>`;
W.statRow = (l, v) => `<div class="stat-row"><span class="label">${l}</span><span class="value">${v}</span></div>`;
W.avatar = (ini, c='') => `<div class="avatar ${c}">${ini}</div>`;
W.toggle = (on=false) => `<div class="toggle ${on?'on':''}"></div>`;
W.flex = (cls, ...items) => `<div style="display:flex" class="${cls}">${items.join('')}</div>`;
W.filterBar = (...f) => `<div class="filter-bar">${f.map((x,i)=>`<span class="filter ${i===0?'active':''}">${x}</span>`).join('')}</div>`;
W.footer = () => `<div class="footer-bar"><span>Sara Electronics © 2026</span><span>Confidential — Internal Use Only</span><span>Wireframe Document v4.0</span></div>`;
